# Build (Compilação)
FROM gcc:latest AS builder

WORKDIR /app
RUN mkdir bin
COPY src/ .

# Compila
RUN for f in *.cpp; do g++ "$f" -static -o "bin/${f%.cpp}"; done

# Execução
FROM debian:stable-slim

WORKDIR /app
COPY --from=builder /app/bin/ .

CMD ["./deadlock"]